name: shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name : multiline
        run: |
          node
          nmp -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python