name: shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: 2echo "Hello World"
      - name: echo a string with a variable
        run: echo "Hello ${{ github.event_name }}"
      - name: multiline script
        run: |
          echo "Hello"
          echo "World"