name: shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"

      - name: installtion
        run: |
          sudo apt-get update
          sudo apt-get install nodejs -y
     
          sudo apt-get install python3 -y
          ls -la

      - name : multiline
        run: |
          node -v
     
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory
        run: Get-Location

      - name: list
        run: dir
        shell: bash